### ISSUE TITLE
ImportError: No module named docker_machinator.dmachinator

### ISSUE THREAD

**Issue by fanis** [realcr/docker_machinator#3]
Running this on the below OS and Python version seems to fail for me:
Python 2.7.15 and pip 18.0.
Windows 10 x64.

```
λ pip install -e .                                                                                                        
Obtaining file:///C:/work/root/docker_machinator                                                                          
Requirement already satisfied: sstash in c:\python27\lib\site-packages (from docker-machinator==0.1) (0.17)               
Requirement already satisfied: jsonschema in c:\python27\lib\site-packages (from sstash->docker-machinator==0.1) (2.6.0)  
Requirement already satisfied: PyNaCl in c:\python27\lib\site-packages (from sstash->docker-machinator==0.1) (1.2.1)      
Requirement already satisfied: functools32; python_version == "2.7" in c:\python27\lib\site-packages (from jsonschema->sst
ash->docker-machinator==0.1) (3.2.3.post2)                                                                                
Requirement already satisfied: six in c:\python27\lib\site-packages (from PyNaCl->sstash->docker-machinator==0.1) (1.11.0)
                                                                                                                          
Requirement already satisfied: cffi>=1.4.1 in c:\python27\lib\site-packages (from PyNaCl->sstash->docker-machinator==0.1) 
(1.11.5)                                                                                                                  
Requirement already satisfied: pycparser in c:\python27\lib\site-packages (from cffi>=1.4.1->PyNaCl->sstash->docker-machin
ator==0.1) (2.18)                                                                                                         
Installing collected packages: docker-machinator                                                                          
  Running setup.py develop for docker-machinator                                                                          
Successfully installed docker-machinator                                                                                  
```
```
λ dmachinator store lb stash
Traceback (most recent call last):
  File "C:\Python27\Scripts\dmachinator-script.py", line 11, in <module>
    load_entry_point('docker-machinator', 'console_scripts', 'dmachinator')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named docker_machinator.dmachinator
```

**Comment by realcr** [comment]
@fanis : thanks for sending this issue!
Could you please check if `docker_machinator` works for you with Python3? (Probably `py -3` on windows)

**Comment by fanis** [comment]
Indeed works with Python 3, thanks!

**Comment by realcr** [comment]
Glad to hear, have fun!
